/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EspaceRouteImport } from './routes/_espace'
import { Route as EspaceAccueilRouteImport } from './routes/_espace.accueil'
import { Route as EspaceAgentEmailRouteImport } from './routes/_espace.agent-email'
import { Route as EspaceCodesClientsRouteImport } from './routes/_espace.codes-clients'
import { Route as EspaceCodesRegimesRouteImport } from './routes/_espace.codes-regimes'
import { Route as EspaceListeFinanceRouteImport } from './routes/_espace.liste-finance'
import { Route as EspaceParametresRouteImport } from './routes/_espace.parametres'
import { Route as EspaceRapportsRouteImport } from './routes/_espace.rapports'
import { Route as EspaceUtilisateursRouteImport } from './routes/_espace.utilisateurs'
import { Route as EspaceClientsIndexRouteImport } from './routes/_espace.clients.index'
import { Route as EspaceClientsClientIdRouteImport } from './routes/_espace.clients.$clientId'
import { Route as EspaceDeclarantsIndexRouteImport } from './routes/_espace.declarants.index'
import { Route as EspaceDeclarantsDeclarantIdRouteImport } from './routes/_espace.declarants.$declarantId'
import { Route as EspaceMainsLeveesIndexRouteImport } from './routes/_espace.mains-levees.index'
import { Route as EspaceMainsLeveesReferenceRouteImport } from './routes/_espace.mains-levees.$reference'
import { Route as EspaceMesDossiersIndexRouteImport } from './routes/_espace.mes-dossiers.index'
import { Route as EspaceMesDossiersReferenceRouteImport } from './routes/_espace.mes-dossiers.$reference'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceRoute = EspaceRouteImport.update({
  id: '/_espace',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceAccueilRoute = EspaceAccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceAgentEmailRoute = EspaceAgentEmailRouteImport.update({
  id: '/agent-email',
  path: '/agent-email',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceCodesClientsRoute = EspaceCodesClientsRouteImport.update({
  id: '/codes-clients',
  path: '/codes-clients',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceCodesRegimesRoute = EspaceCodesRegimesRouteImport.update({
  id: '/codes-regimes',
  path: '/codes-regimes',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceListeFinanceRoute = EspaceListeFinanceRouteImport.update({
  id: '/liste-finance',
  path: '/liste-finance',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceParametresRoute = EspaceParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceRapportsRoute = EspaceRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceUtilisateursRoute = EspaceUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceClientsIndexRoute = EspaceClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceClientsClientIdRoute = EspaceClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceDeclarantsIndexRoute = EspaceDeclarantsIndexRouteImport.update({
  id: '/declarants/',
  path: '/declarants/',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceDeclarantsDeclarantIdRoute =
  EspaceDeclarantsDeclarantIdRouteImport.update({
    id: '/declarants/$declarantId',
    path: '/declarants/$declarantId',
    getParentRoute: () => EspaceRoute,
  } as any)
const EspaceMainsLeveesIndexRoute = EspaceMainsLeveesIndexRouteImport.update({
  id: '/mains-levees/',
  path: '/mains-levees/',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceMainsLeveesReferenceRoute =
  EspaceMainsLeveesReferenceRouteImport.update({
    id: '/mains-levees/$reference',
    path: '/mains-levees/$reference',
    getParentRoute: () => EspaceRoute,
  } as any)
const EspaceMesDossiersIndexRoute = EspaceMesDossiersIndexRouteImport.update({
  id: '/mes-dossiers/',
  path: '/mes-dossiers/',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceMesDossiersReferenceRoute =
  EspaceMesDossiersReferenceRouteImport.update({
    id: '/mes-dossiers/$reference',
    path: '/mes-dossiers/$reference',
    getParentRoute: () => EspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accueil': typeof EspaceAccueilRoute
  '/agent-email': typeof EspaceAgentEmailRoute
  '/codes-clients': typeof EspaceCodesClientsRoute
  '/codes-regimes': typeof EspaceCodesRegimesRoute
  '/liste-finance': typeof EspaceListeFinanceRoute
  '/parametres': typeof EspaceParametresRoute
  '/rapports': typeof EspaceRapportsRoute
  '/utilisateurs': typeof EspaceUtilisateursRoute
  '/clients/$clientId': typeof EspaceClientsClientIdRoute
  '/declarants/$declarantId': typeof EspaceDeclarantsDeclarantIdRoute
  '/mains-levees/$reference': typeof EspaceMainsLeveesReferenceRoute
  '/mes-dossiers/$reference': typeof EspaceMesDossiersReferenceRoute
  '/clients/': typeof EspaceClientsIndexRoute
  '/declarants/': typeof EspaceDeclarantsIndexRoute
  '/mains-levees/': typeof EspaceMainsLeveesIndexRoute
  '/mes-dossiers/': typeof EspaceMesDossiersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accueil': typeof EspaceAccueilRoute
  '/agent-email': typeof EspaceAgentEmailRoute
  '/codes-clients': typeof EspaceCodesClientsRoute
  '/codes-regimes': typeof EspaceCodesRegimesRoute
  '/liste-finance': typeof EspaceListeFinanceRoute
  '/parametres': typeof EspaceParametresRoute
  '/rapports': typeof EspaceRapportsRoute
  '/utilisateurs': typeof EspaceUtilisateursRoute
  '/clients/$clientId': typeof EspaceClientsClientIdRoute
  '/declarants/$declarantId': typeof EspaceDeclarantsDeclarantIdRoute
  '/mains-levees/$reference': typeof EspaceMainsLeveesReferenceRoute
  '/mes-dossiers/$reference': typeof EspaceMesDossiersReferenceRoute
  '/clients': typeof EspaceClientsIndexRoute
  '/declarants': typeof EspaceDeclarantsIndexRoute
  '/mains-levees': typeof EspaceMainsLeveesIndexRoute
  '/mes-dossiers': typeof EspaceMesDossiersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_espace': typeof EspaceRouteWithChildren
  '/_espace/accueil': typeof EspaceAccueilRoute
  '/_espace/agent-email': typeof EspaceAgentEmailRoute
  '/_espace/codes-clients': typeof EspaceCodesClientsRoute
  '/_espace/codes-regimes': typeof EspaceCodesRegimesRoute
  '/_espace/liste-finance': typeof EspaceListeFinanceRoute
  '/_espace/parametres': typeof EspaceParametresRoute
  '/_espace/rapports': typeof EspaceRapportsRoute
  '/_espace/utilisateurs': typeof EspaceUtilisateursRoute
  '/_espace/clients/$clientId': typeof EspaceClientsClientIdRoute
  '/_espace/declarants/$declarantId': typeof EspaceDeclarantsDeclarantIdRoute
  '/_espace/mains-levees/$reference': typeof EspaceMainsLeveesReferenceRoute
  '/_espace/mes-dossiers/$reference': typeof EspaceMesDossiersReferenceRoute
  '/_espace/clients/': typeof EspaceClientsIndexRoute
  '/_espace/declarants/': typeof EspaceDeclarantsIndexRoute
  '/_espace/mains-levees/': typeof EspaceMainsLeveesIndexRoute
  '/_espace/mes-dossiers/': typeof EspaceMesDossiersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accueil'
    | '/agent-email'
    | '/codes-clients'
    | '/codes-regimes'
    | '/liste-finance'
    | '/parametres'
    | '/rapports'
    | '/utilisateurs'
    | '/clients/$clientId'
    | '/declarants/$declarantId'
    | '/mains-levees/$reference'
    | '/mes-dossiers/$reference'
    | '/clients/'
    | '/declarants/'
    | '/mains-levees/'
    | '/mes-dossiers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accueil'
    | '/agent-email'
    | '/codes-clients'
    | '/codes-regimes'
    | '/liste-finance'
    | '/parametres'
    | '/rapports'
    | '/utilisateurs'
    | '/clients/$clientId'
    | '/declarants/$declarantId'
    | '/mains-levees/$reference'
    | '/mes-dossiers/$reference'
    | '/clients'
    | '/declarants'
    | '/mains-levees'
    | '/mes-dossiers'
  id:
    | '__root__'
    | '/'
    | '/_espace'
    | '/_espace/accueil'
    | '/_espace/agent-email'
    | '/_espace/codes-clients'
    | '/_espace/codes-regimes'
    | '/_espace/liste-finance'
    | '/_espace/parametres'
    | '/_espace/rapports'
    | '/_espace/utilisateurs'
    | '/_espace/clients/$clientId'
    | '/_espace/declarants/$declarantId'
    | '/_espace/mains-levees/$reference'
    | '/_espace/mes-dossiers/$reference'
    | '/_espace/clients/'
    | '/_espace/declarants/'
    | '/_espace/mains-levees/'
    | '/_espace/mes-dossiers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EspaceRoute: typeof EspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_espace': {
      id: '/_espace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof EspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_espace/accueil': {
      id: '/_espace/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof EspaceAccueilRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/_espace/agent-email': {
      id: '/_espace/agent-email'
      path: '/agent-email'
      fullPath: '/agent-email'
      preLoaderRoute: typeof EspaceAgentEmailRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/_espace/codes-clients': {
      id: '/_espace/codes-clients'
      path: '/codes-clients'
      fullPath: '/codes-clients'
      preLoaderRoute: typeof EspaceCodesClientsRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/_espace/codes-regimes': {
      id: '/_espace/codes-regimes'
      path: '/codes-regimes'
      fullPath: '/codes-regimes'
      preLoaderRoute: typeof EspaceCodesRegimesRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/_espace/liste-finance': {
      id: '/_espace/liste-finance'
      path: '/liste-finance'
      fullPath: '/liste-finance'
      preLoaderRoute: typeof EspaceListeFinanceRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/_espace/parametres': {
      id: '/_espace/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof EspaceParametresRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/_espace/rapports': {
      id: '/_espace/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof EspaceRapportsRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/_espace/utilisateurs': {
      id: '/_espace/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof EspaceUtilisateursRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/_espace/clients/': {
      id: '/_espace/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof EspaceClientsIndexRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/_espace/clients/$clientId': {
      id: '/_espace/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof EspaceClientsClientIdRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/_espace/declarants/': {
      id: '/_espace/declarants/'
      path: '/declarants'
      fullPath: '/declarants/'
      preLoaderRoute: typeof EspaceDeclarantsIndexRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/_espace/declarants/$declarantId': {
      id: '/_espace/declarants/$declarantId'
      path: '/declarants/$declarantId'
      fullPath: '/declarants/$declarantId'
      preLoaderRoute: typeof EspaceDeclarantsDeclarantIdRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/_espace/mains-levees/': {
      id: '/_espace/mains-levees/'
      path: '/mains-levees'
      fullPath: '/mains-levees/'
      preLoaderRoute: typeof EspaceMainsLeveesIndexRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/_espace/mains-levees/$reference': {
      id: '/_espace/mains-levees/$reference'
      path: '/mains-levees/$reference'
      fullPath: '/mains-levees/$reference'
      preLoaderRoute: typeof EspaceMainsLeveesReferenceRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/_espace/mes-dossiers/': {
      id: '/_espace/mes-dossiers/'
      path: '/mes-dossiers'
      fullPath: '/mes-dossiers/'
      preLoaderRoute: typeof EspaceMesDossiersIndexRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/_espace/mes-dossiers/$reference': {
      id: '/_espace/mes-dossiers/$reference'
      path: '/mes-dossiers/$reference'
      fullPath: '/mes-dossiers/$reference'
      preLoaderRoute: typeof EspaceMesDossiersReferenceRouteImport
      parentRoute: typeof EspaceRoute
    }
  }
}

interface EspaceRouteChildren {
  EspaceAccueilRoute: typeof EspaceAccueilRoute
  EspaceAgentEmailRoute: typeof EspaceAgentEmailRoute
  EspaceCodesClientsRoute: typeof EspaceCodesClientsRoute
  EspaceCodesRegimesRoute: typeof EspaceCodesRegimesRoute
  EspaceListeFinanceRoute: typeof EspaceListeFinanceRoute
  EspaceParametresRoute: typeof EspaceParametresRoute
  EspaceRapportsRoute: typeof EspaceRapportsRoute
  EspaceUtilisateursRoute: typeof EspaceUtilisateursRoute
  EspaceClientsClientIdRoute: typeof EspaceClientsClientIdRoute
  EspaceDeclarantsDeclarantIdRoute: typeof EspaceDeclarantsDeclarantIdRoute
  EspaceMainsLeveesReferenceRoute: typeof EspaceMainsLeveesReferenceRoute
  EspaceMesDossiersReferenceRoute: typeof EspaceMesDossiersReferenceRoute
  EspaceClientsIndexRoute: typeof EspaceClientsIndexRoute
  EspaceDeclarantsIndexRoute: typeof EspaceDeclarantsIndexRoute
  EspaceMainsLeveesIndexRoute: typeof EspaceMainsLeveesIndexRoute
  EspaceMesDossiersIndexRoute: typeof EspaceMesDossiersIndexRoute
}

const EspaceRouteChildren: EspaceRouteChildren = {
  EspaceAccueilRoute: EspaceAccueilRoute,
  EspaceAgentEmailRoute: EspaceAgentEmailRoute,
  EspaceCodesClientsRoute: EspaceCodesClientsRoute,
  EspaceCodesRegimesRoute: EspaceCodesRegimesRoute,
  EspaceListeFinanceRoute: EspaceListeFinanceRoute,
  EspaceParametresRoute: EspaceParametresRoute,
  EspaceRapportsRoute: EspaceRapportsRoute,
  EspaceUtilisateursRoute: EspaceUtilisateursRoute,
  EspaceClientsClientIdRoute: EspaceClientsClientIdRoute,
  EspaceDeclarantsDeclarantIdRoute: EspaceDeclarantsDeclarantIdRoute,
  EspaceMainsLeveesReferenceRoute: EspaceMainsLeveesReferenceRoute,
  EspaceMesDossiersReferenceRoute: EspaceMesDossiersReferenceRoute,
  EspaceClientsIndexRoute: EspaceClientsIndexRoute,
  EspaceDeclarantsIndexRoute: EspaceDeclarantsIndexRoute,
  EspaceMainsLeveesIndexRoute: EspaceMainsLeveesIndexRoute,
  EspaceMesDossiersIndexRoute: EspaceMesDossiersIndexRoute,
}

const EspaceRouteWithChildren =
  EspaceRoute._addFileChildren(EspaceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EspaceRoute: EspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
